In [15]:
import numpy as np

Creating array from list

In [16]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("Array 1D:", arr_1d)
arr_2d = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])
print("Array 2D:", arr_2d)

Array 1D: [1 2 3 4 5]
Array 2D: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


 List vs numpy array

In [17]:
py_list = [1, 2, 3, 4, 5]   
print("Python List:", py_list*3)

np_array = np.array([1, 2, 3, 4, 5]) #element-wise mutliplication
print("NumPy Array:", np_array*3)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("Python list time taken:", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("NumPy array time taken:", time.time() - start)

Python List: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
NumPy Array: [ 3  6  9 12 15]
Python list time taken: 0.07322859764099121
NumPy array time taken: 0.006685495376586914


Creating Array from scratch

In [18]:
zero = np.zeros((3,4))
print("Zeros Array:\n", zero)

one = np.ones((2,3))
print("Ones Array:\n", one)

full = np.full((2,2), 7)
print("Full Array:\n", full)

random = np.random.rand(3,3)
print("Random Array:\n", random)

sequence = np.arange(10, 21, 2)
print("Sequence Array:", sequence)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array:
 [[7 7]
 [7 7]]
Random Array:
 [[0.98930365 0.54243319 0.76029425]
 [0.74753298 0.14555904 0.28269917]
 [0.42565358 0.65750779 0.4406185 ]]
Sequence Array: [10 12 14 16 18 20]


Vector , Matrix and Tensor

In [19]:
vector = np.array([1, 2, 3])
print("Vector:", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:\n", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)

Vector: [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array Shape:", arr.shape)
print("Array Data Type:", arr.dtype)
print("Array Size:", arr.size)
print("Array Number of Dimensions:", arr.ndim)

Array Shape: (2, 3)
Array Data Type: int64
Array Size: 6
Array Number of Dimensions: 2


Array Reshaping

In [ ]:
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8 ,9, 10, 11, 12])
print("Original Array:\n", ar)

reshaped_arr = ar.reshape(3, 4)
print("Reshaped Array (4x2):\n", reshaped_arr)

flat = reshaped_arr.flatten()
print("Flattened Array:", flat)

#returns view of original array whenever possible
reavl = reshaped_arr.ravel()
print("Raveled Array:", reavl)

transposed = reshaped_arr.T
print("Transposed Array:\n", transposed)


Original Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array (4x2):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Raveled Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Transposed Array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
