In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.random.rand(5)
arr3 = np.ones((3, 3))


In [6]:
np.save('array1.npy', arr1)
np.save('array2.npy', arr2)
np.save('array3.npy', arr3)

In [7]:
load_arr1 = np.load('array1.npy')
print(load_arr1)
load_arr2 = np.load('array2.npy') 
print(load_arr2)  
load_arr3 = np.load('array3.npy')
print(load_arr3)

[1 2 3 4 5]
[0.56163903 0.16410632 0.7443054  0.6932867  0.67919245]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
try:
    logo = np.load('numpy.svg.npy')
    #Display
    plt.Figure(figsize=(5,5))
    plt.Subplot(121)
    plt.show(logo)
    plt.title('NumPy Logo Image')
    plt.grid(False)

    dark_logo = 1 - logo
    plt.Subplot(122)
    plt.show(dark_logo)
    plt.title('Dark NumPy Logo Image')
    plt.grid(False)
except FileNotFoundError:
    print("File not found. Please check the file path and try again.")

File not found. Please check the file path and try again.
