NumPy array operation

In [89]:
import numpy as np

In [90]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing:", arr[2:6])
print("with step:", arr[1:8:2])
print("Negative Indexing:", arr[-5:-1])

Basic Slicing: [3 4 5 6]
with step: [2 4 6 8]
Negative Indexing: [6 7 8 9]


In [91]:
arr2 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("2D Array Slicing:\n", arr2[0:2, 1:3])
print("Entire row slice:\n", arr2[1])
print("Entire column slice:\n", arr2[:, 2])

2D Array Slicing:
 [[2 3]
 [5 6]]
Entire row slice:
 [4 5 6]
Entire column slice:
 [3 6 9]


Sorting

In [92]:
unshorted = np.array([3, 1, 4, 2, 5])
print("Sorted array:", np.sort(unshorted))

unshorted2D = np.array([[3, 1, 4],
                        [2, 5, 0]]) 
print("Sorted 2D array along axis 0:\n", np.sort(unshorted2D, axis=0))
print("Sorted 2D array along axis 1:\n", np.sort(unshorted2D, axis=1))

Sorted array: [1 2 3 4 5]
Sorted 2D array along axis 0:
 [[2 1 0]
 [3 5 4]]
Sorted 2D array along axis 1:
 [[1 3 4]
 [0 2 5]]


Filter

In [93]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
even = num[num %2 == 0]
print("Even number",even)

Even number [ 2  4  6  8 10]


Filter with mask

In [94]:
mask = 5<num
print("Number greater than 5:", num[mask])

Number greater than 5: [ 6  7  8  9 10]


Fancing Indexing vs np.where()

In [95]:
indices = [1, 3, 5]
print("Fancing Indexing:", num[indices])

where_res = np.where(num > 5)
print("np.where() result:", num[where_res])

Fancing Indexing: [2 4 6]
np.where() result: [ 6  7  8  9 10]


In [96]:
condit_arr = np.where(num > 5 , num*2, num)
print("Conditional array (num>5 ? num*2 : num):", condit_arr)

Conditional array (num>5 ? num*2 : num): [ 1  2  3  4  5 12 14 16 18 20]


Adding and removing data

In [97]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
ccmbined = np.concatenate((arr1, arr2))
print("Concatenated array:", ccmbined)

Concatenated array: [1 2 3 4 5 6]


Array compatiblity

In [98]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])  
C = np.array([8, 9, 10])    
print("A and B compatible:", A.shape == B.shape)
print("A and C compatible:", A.shape == C.shape)
print("B and C compatible:", B.shape == C.shape)

A and B compatible: True
A and C compatible: True
B and C compatible: True


In [99]:
orignal = np.array([[1, 2, 3], [4, 5, 6]])
new_row = np.array([[7, 8, 9]])
expanded = np.vstack((orignal, new_row)) # row add using vstack
print("Array after adding new row:\n", expanded)

new_col = np.array([[10], [11], [12]])
expanded_col = np.hstack((expanded, new_col)) # column add using hstack
print("Array after adding new column:\n", expanded_col)


Array after adding new row:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after adding new column:
 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [100]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
removed_row = np.delete(arr,2) # remove first row
print("Array after removing element at index 2:\n", removed_row)    

Array after removing element at index 2:
 [1 2 4 5 6]
